sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2

services:
  - mysql
  - postgresql

env:
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS friendly_fk_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE friendly_fk_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS friendly_fk_test; CREATE DATABASE IF NOT EXISTS friendly_fk_test;'; fi"

before_install: gem install bundler -v 1.16.6
script:
 - bundle exec rspec spec
 - bundle exec rubocop
