postgres:
  adapter: postgresql
  database: friendly_fk_test
  username: postgres
  encoding: utf8

mysql:
  adapter: mysql2
  database: friendly_fk_test
  username: test_user
  password: test_user
  encoding: utf8
  host: localhost
  port: 3306
