name: ci

on:
  push: {}

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby
      
      - name: Run rubocop
        run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby

      - name: Run RSpec
        run: bundle exec rspec spec
