name: ci

on:
  push: {}

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      
      - name: Run rubocop
        run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Run RSpec
        run: bundle exec rspec spec
