name: RSpec on MySQL

permissions:
  contents: read
  pull-requests: write

on:
  push: {}

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    env:
      TEST_DATABASE_URL: mysql2://root:root@localhost:3306/friendly_fk_test
      DB: mysql
      RAILS_ENV: test

    steps:
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE friendly_fk_test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec spec
