name: RSpec on MySQL

on:
  push: {}

jobs:
  rspec:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']

    env:
      TEST_DATABASE_URL: mysql2://root:root@localhost:3306
      DB: mysql
      RAILS_ENV: test

    steps:
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE friendly_fk_test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec spec
