name: RSpec on Postgres

permissions:
  contents: read
  pull-requests: write

on:
  push: {}

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    env:
      TEST_DATABASE_URL: postgres://test_user:test_user@localhost:5432/friendly_fk_test
      RAILS_ENV: test

    services:
      database:
        image: postgres:12-alpine
        env:
          POSTGRES_DB: friendly_fk_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_user
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec spec
