name: RSpec on MySQL

on:
  push: {}

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        mysql-version: ['5.7']

    env:
      TEST_DATABASE_URL: mysql2://test_user:test_user@database:3306
      DB: mysql
      RAILS_ENV: test

    services:
      database:
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_DATABASE: friendly_fk_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_user
        ports:
          - 3306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec spec
